import numpy as np
log_template = {
    'Lodge Pickup Plan': {'event_attribute': ['ocel_activity', 'ocel_type_Pickup_Plan', 'ocel_type_Cargo'],
                                'event_template': '{{ocel_activity}} {{ocel_type_Pickup_Plan}} {{ocel_type_Cargo}}',
                  },
    np.nan: {'event_attribute': ['ocel_activity'],
                                'event_template': 'Assign Truck',
                  },
    'Enter the port': {'event_attribute': ['ocel_activity', 'ocel_type_Truck'],
                                'event_template': '{{ocel_activity}} {{ocel_type_Truck}}',
                  },
    'Weigh the Empty Truck': {'event_attribute': ['ocel_activity', 'ocel_type_Truck'],
                                'event_template': '{{ocel_activity}} {{ocel_type_Truck}}',
                  },
    'Check Empty Truck Weight Abnormality': {'event_attribute': ['ocel_activity', 'ocel_type_Truck'],
                                'event_template': '{{ocel_activity}} {{ocel_type_Truck}}',
                  },
    'Fail to Weigh': {'event_attribute': ['ocel_activity', 'ocel_type_Truck'],
                                'event_template': '{{ocel_activity}} {{ocel_type_Truck}}',
                  },


    'Arrive at the Silo': {'event_attribute': ['ocel_activity', ''],
                                'event_template': '{{ocel_activity}} {{}}',
                  },
    'Determine the Continuance of the Pickup': {'event_attribute': ['ocel_activity', ''],
                                'event_template': '{{ocel_activity}} {{}}',
                  },
    'Fail to Load': {'event_attribute': ['ocel_activity', ''],
                                'event_template': '{{ocel_activity}} {{}}',
                  },


    'Load Truck': {'event_attribute': ['ocel_activity', 'ocel_type_Truck'],
                                'event_template': '{{ocel_activity}} {{ocel_type_Truck}}',
                  },
    'Weigh the Loaded Truck': {'event_attribute': ['ocel_activity', 'ocel_type_Truck'],
                                'event_template': '{{ocel_activity}} {{ocel_type_Truck}}',
                  },
    'Evaluate the Truck Exit': {'event_attribute': ['ocel_activity', 'ocel_type_Truck'],
                                'event_template': '{{ocel_activity}} {{ocel_type_Truck}}',
                  },
    'Input the Tally Sheet': {'event_attribute': ['ocel_activity', 'ocel_type_Truck'],
                                'event_template': '{{ocel_activity}} {{ocel_type_Truck}}',
                  },
    'Print the Weighing Ticket': {'event_attribute': ['ocel_activity', 'ocel_type_Truck'],
                                'event_template': '{{ocel_activity}} {{ocel_type_Truck}}',
                  }
    }