log_template = {
    'pay order': {'event_attribute': ['ocel_activity', 'ocel_type_products'],
                  'event_template': '{{ocel_activity}} {{ocel_type_products}}',
                  },
                
    'package delivered':{'event_attribute': ['ocel_activity', 'ocel_type_products', 'ocel_type_employees', 'ocel_type_packages'],
                     'event_template': '{{ocel_activity}} {{ocel_type_products}} {{ocel_type_employees}} {{ocel_type_packages}}',
                  },
    'place order':{'event_attribute': ['ocel_activity', 'ocel_type_customers', 'ocel_type_products'],
                     'event_template': '{{ocel_activity}} {{ocel_type_customers}} {{ocel_type_products}}',
                  },
    'create package':{'event_attribute': ['ocel_activity', 'ocel_type_products', 'ocel_type_employees', 'ocel_type_packages'],
                     'event_template': '{{ocel_activity}} {{ocel_type_products}} {{ocel_type_employees}} {{ocel_type_packages}}',
                  },
    'confirm order':{'event_attribute': ['ocel_activity', 'ocel_type_customers', 'ocel_type_products', 'ocel_type_employees'],
                     'event_template': '{{ocel_activity}} {{ocel_type_customers}} {{ocel_type_products}} {{ocel_type_employees}}',
                  },
    'item out of stock':{'event_attribute': ['ocel_activity', 'ocel_type_products', 'ocel_type_employees'],
                     'event_template': '{{ocel_activity}} {{ocel_type_products}} {{ocel_type_employees}}',
                  },
    'pick item':{'event_attribute': ['ocel_activity', 'ocel_type_employees', 'ocel_type_products'],
                  'event_template': '{{ocel_activity}} {{ocel_type_employees}} {{ocel_type_products}}',
                  },
    'send package':{'event_attribute': ['ocel_activity', 'ocel_type_products', 'ocel_type_employees', 'ocel_type_packages'],
                     'event_template': '{{ocel_activity}} {{ocel_type_products}} {{ocel_type_employees}} {{ocel_type_packages}}',
                  },
    'payment reminder':{'event_attribute': ['ocel_activity', 'ocel_type_products'],
                  'event_template': '{{ocel_activity}} {{ocel_type_products}}',
                  },
    'reorder item':{'event_attribute': ['ocel_activity', 'ocel_type_products', 'ocel_type_employees'],
                     'event_template': '{{ocel_activity}} {{ocel_type_products}} {{ocel_type_employees}}',
                  },
    'failed delivery':{'event_attribute': ['ocel_activity', 'ocel_type_customers', 'ocel_type_products', 'ocel_type_employees', 'ocel_type_packages'],
                     'event_template': '{{ocel_activity}} {{ocel_type_customers}} {{ocel_type_products}} {{ocel_type_employees}} {{ocel_type_packages}}',
                  }

}
