log_template = {
    'Register Customer Order': {'event_attribute': ['ocel_activity', 'ocel_type_Customer_Order'],
                                'event_template': '{{ocel_activity}} {{ocel_type_Customer_Order}}',
                  },
                
    'Create Transport Document':{'event_attribute': ['ocel_activity', 'ocel_type_Customer_Order', 'ocel_type_Transport_Document'],
                                 'event_template': '{{ocel_activity}} {{ocel_type_Customer_Order}} {{ocel_type_Transport_Document}}',
                  },
    'Book Vehicles':{'event_attribute': ['ocel_activity', 'ocel_type_Transport_Document', 'ocel_type_Vehicle'],
                     'event_template': '{{ocel_activity}}  {{ocel_type_Transport_Document}} {{ocel_type_Vehicle}}',
                  },
    'Order Empty Containers':{'event_attribute': ['ocel_activity', 'ocel_type_Transport_Document', 'ocel_type_Container'],
                     'event_template': '{{ocel_activity}} {{ocel_type_Transport_Document}} {{ocel_type_Container}}',
                  },
    'Pick Up Empty Container':{'event_attribute': ['ocel_activity', 'ocel_type_Container'],
                     'event_template': '{{ocel_activity}}  {{ocel_type_Container}}',
                  },
    'Collect Goods':{'event_attribute': ['ocel_activity', 'ocel_type_Handling_Unit'],
                     'event_template': '{{ocel_activity}} {{ocel_type_Handling_Unit}}',
                  },
    'Load Truck':{'event_attribute': ['ocel_activity', 'ocel_type_Container', 'ocel_type_Handling_Unit', 'ocel_type_Truck'],
                  'event_template': '{{ocel_activity}} {{ocel_type_Container}} {{ocel_type_Handling_Unit}} {{ocel_type_Truck}}',
                  },
    'Drive to Terminal':{'event_attribute': ['ocel_activity', 'ocel_type_Container', 'ocel_type_Truck'],
                     'event_template': '{{ocel_activity}} {{ocel_type_Container}} {{ocel_type_Truck}}',
                  },
    'Weigh':{'event_attribute': ['ocel_activity', 'ocel_type_Container', 'ocel_type_Forklift'],
                  'event_template': '{{ocel_activity}} {{ocel_type_Container}} {{ocel_type_Forklift}}',
                  },   
    'Place in Stock':{'event_attribute': ['ocel_activity', 'ocel_type_Container', 'ocel_type_Forklift'],
                  'event_template': '{{ocel_activity}} {{ocel_type_Container}} {{ocel_type_Forklift}}',
                  },
    'Bring to Loading Bay':{'event_attribute': ['ocel_activity', 'ocel_type_Container', 'ocel_type_Forklift'],
                  'event_template': '{{ocel_activity}} {{ocel_type_Container}} {{ocel_type_Forklift}}',
                  },
    'Load to Vehicle':{'event_attribute': ['ocel_activity', 'ocel_type_Vehicle', 'ocel_type_Container', 'ocel_type_Forklift'],
                  'event_template': '{{ocel_activity}} {{ocel_type_Vehicle}} {{ocel_type_Container}} {{ocel_type_Forklift}}',
                  },
    'Reschedule Container':{'event_attribute': ['ocel_activity',  'ocel_type_Transport_Document', 'ocel_type_Vehicle', 'ocel_type_Container'],
                     'event_template': '{{ocel_activity}} {{ocel_type_Transport_Document}} {{ocel_type_Vehicle}} {{ocel_type_Container}}',
                  },
    'Depart':{'event_attribute': ['ocel_activity', 'ocel_type_Transport_Document', 'ocel_type_Vehicle', 'ocel_type_Container'],
                     'event_template': '{{ocel_activity}} {{ocel_type_Transport_Document}} {{ocel_type_Vehicle}} {{ocel_type_Container}}',
                  },
   

}
